// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: SocketCommon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// request and response command
type SocketCommon_Command int32

const (
	SocketCommon_UNKNOWN     SocketCommon_Command = 0
	SocketCommon_CONNECT     SocketCommon_Command = 1
	SocketCommon_CONNECTED   SocketCommon_Command = 2
	SocketCommon_SEND        SocketCommon_Command = 3
	SocketCommon_SUBSCRIBE   SocketCommon_Command = 4
	SocketCommon_UNSUBSCRIBE SocketCommon_Command = 5
	SocketCommon_DISCONNECT  SocketCommon_Command = 6
	SocketCommon_MESSAGE     SocketCommon_Command = 7
	SocketCommon_HEARTBEAT   SocketCommon_Command = 8
	SocketCommon_ERROR       SocketCommon_Command = 9
)

// Enum value maps for SocketCommon_Command.
var (
	SocketCommon_Command_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONNECT",
		2: "CONNECTED",
		3: "SEND",
		4: "SUBSCRIBE",
		5: "UNSUBSCRIBE",
		6: "DISCONNECT",
		7: "MESSAGE",
		8: "HEARTBEAT",
		9: "ERROR",
	}
	SocketCommon_Command_value = map[string]int32{
		"UNKNOWN":     0,
		"CONNECT":     1,
		"CONNECTED":   2,
		"SEND":        3,
		"SUBSCRIBE":   4,
		"UNSUBSCRIBE": 5,
		"DISCONNECT":  6,
		"MESSAGE":     7,
		"HEARTBEAT":   8,
		"ERROR":       9,
	}
)

func (x SocketCommon_Command) Enum() *SocketCommon_Command {
	p := new(SocketCommon_Command)
	*p = x
	return p
}

func (x SocketCommon_Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocketCommon_Command) Descriptor() protoreflect.EnumDescriptor {
	return file_SocketCommon_proto_enumTypes[0].Descriptor()
}

func (SocketCommon_Command) Type() protoreflect.EnumType {
	return &file_SocketCommon_proto_enumTypes[0]
}

func (x SocketCommon_Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocketCommon_Command.Descriptor instead.
func (SocketCommon_Command) EnumDescriptor() ([]byte, []int) {
	return file_SocketCommon_proto_rawDescGZIP(), []int{0, 0}
}

// data type
type SocketCommon_DataType int32

const (
	SocketCommon_Unknown          SocketCommon_DataType = 0
	SocketCommon_Quote            SocketCommon_DataType = 1
	SocketCommon_Option           SocketCommon_DataType = 2
	SocketCommon_Future           SocketCommon_DataType = 3
	SocketCommon_QuoteDepth       SocketCommon_DataType = 4
	SocketCommon_TradeTick        SocketCommon_DataType = 5
	SocketCommon_Asset            SocketCommon_DataType = 6
	SocketCommon_Position         SocketCommon_DataType = 7
	SocketCommon_OrderStatus      SocketCommon_DataType = 8
	SocketCommon_OrderTransaction SocketCommon_DataType = 9
	SocketCommon_StockTop         SocketCommon_DataType = 10
	SocketCommon_OptionTop        SocketCommon_DataType = 11
	SocketCommon_Kline            SocketCommon_DataType = 12
	SocketCommon_Cc               SocketCommon_DataType = 13
)

// Enum value maps for SocketCommon_DataType.
var (
	SocketCommon_DataType_name = map[int32]string{
		0:  "Unknown",
		1:  "Quote",
		2:  "Option",
		3:  "Future",
		4:  "QuoteDepth",
		5:  "TradeTick",
		6:  "Asset",
		7:  "Position",
		8:  "OrderStatus",
		9:  "OrderTransaction",
		10: "StockTop",
		11: "OptionTop",
		12: "Kline",
		13: "Cc",
	}
	SocketCommon_DataType_value = map[string]int32{
		"Unknown":          0,
		"Quote":            1,
		"Option":           2,
		"Future":           3,
		"QuoteDepth":       4,
		"TradeTick":        5,
		"Asset":            6,
		"Position":         7,
		"OrderStatus":      8,
		"OrderTransaction": 9,
		"StockTop":         10,
		"OptionTop":        11,
		"Kline":            12,
		"Cc":               13,
	}
)

func (x SocketCommon_DataType) Enum() *SocketCommon_DataType {
	p := new(SocketCommon_DataType)
	*p = x
	return p
}

func (x SocketCommon_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocketCommon_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_SocketCommon_proto_enumTypes[1].Descriptor()
}

func (SocketCommon_DataType) Type() protoreflect.EnumType {
	return &file_SocketCommon_proto_enumTypes[1]
}

func (x SocketCommon_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocketCommon_DataType.Descriptor instead.
func (SocketCommon_DataType) EnumDescriptor() ([]byte, []int) {
	return file_SocketCommon_proto_rawDescGZIP(), []int{0, 1}
}

type SocketCommon_QuoteType int32

const (
	SocketCommon_None  SocketCommon_QuoteType = 0
	SocketCommon_BASIC SocketCommon_QuoteType = 1 // basic quote data
	SocketCommon_BBO   SocketCommon_QuoteType = 2 // best bid and offer(include fields: askSize,askPrice,bidSize,bizePrice)
	SocketCommon_ALL   SocketCommon_QuoteType = 3 // include BASIC AND BBO
)

// Enum value maps for SocketCommon_QuoteType.
var (
	SocketCommon_QuoteType_name = map[int32]string{
		0: "None",
		1: "BASIC",
		2: "BBO",
		3: "ALL",
	}
	SocketCommon_QuoteType_value = map[string]int32{
		"None":  0,
		"BASIC": 1,
		"BBO":   2,
		"ALL":   3,
	}
)

func (x SocketCommon_QuoteType) Enum() *SocketCommon_QuoteType {
	p := new(SocketCommon_QuoteType)
	*p = x
	return p
}

func (x SocketCommon_QuoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SocketCommon_QuoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_SocketCommon_proto_enumTypes[2].Descriptor()
}

func (SocketCommon_QuoteType) Type() protoreflect.EnumType {
	return &file_SocketCommon_proto_enumTypes[2]
}

func (x SocketCommon_QuoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SocketCommon_QuoteType.Descriptor instead.
func (SocketCommon_QuoteType) EnumDescriptor() ([]byte, []int) {
	return file_SocketCommon_proto_rawDescGZIP(), []int{0, 2}
}

type SocketCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SocketCommon) Reset() {
	*x = SocketCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SocketCommon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocketCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketCommon) ProtoMessage() {}

func (x *SocketCommon) ProtoReflect() protoreflect.Message {
	mi := &file_SocketCommon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketCommon.ProtoReflect.Descriptor instead.
func (*SocketCommon) Descriptor() ([]byte, []int) {
	return file_SocketCommon_proto_rawDescGZIP(), []int{0}
}

var File_SocketCommon_proto protoreflect.FileDescriptor

var file_SocketCommon_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x34, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x67, 0x65, 0x72, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x62, 0x22, 0xa4, 0x03, 0x0a, 0x0c, 0x53,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x44, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55,
	0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53,
	0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x49,
	0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45,
	0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45, 0x41, 0x52, 0x54,
	0x42, 0x45, 0x41, 0x54, 0x10, 0x08, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x09, 0x22, 0xc9, 0x01, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x75, 0x74, 0x75, 0x72, 0x65, 0x10, 0x03, 0x12, 0x0e,
	0x0a, 0x0a, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x65, 0x70, 0x74, 0x68, 0x10, 0x04, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x72, 0x61, 0x64, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x10, 0x05, 0x12, 0x09, 0x0a,
	0x05, 0x41, 0x73, 0x73, 0x65, 0x74, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x10, 0x07, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x10, 0x08, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x09, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x54, 0x6f, 0x70, 0x10, 0x0a, 0x12, 0x0d, 0x0a, 0x09, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x70, 0x10, 0x0b, 0x12, 0x09, 0x0a, 0x05, 0x4b, 0x6c,
	0x69, 0x6e, 0x65, 0x10, 0x0c, 0x12, 0x06, 0x0a, 0x02, 0x43, 0x63, 0x10, 0x0d, 0x22, 0x32, 0x0a,
	0x09, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x41, 0x53, 0x49, 0x43, 0x10, 0x01, 0x12,
	0x07, 0x0a, 0x03, 0x42, 0x42, 0x4f, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10,
	0x03, 0x42, 0x68, 0x0a, 0x34, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x67, 0x65, 0x72, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x62, 0x50, 0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x67, 0x65, 0x72, 0x66, 0x69, 0x6e,
	0x74, 0x65, 0x63, 0x68, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2d,
	0x73, 0x64, 0x6b, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_SocketCommon_proto_rawDescOnce sync.Once
	file_SocketCommon_proto_rawDescData = file_SocketCommon_proto_rawDesc
)

func file_SocketCommon_proto_rawDescGZIP() []byte {
	file_SocketCommon_proto_rawDescOnce.Do(func() {
		file_SocketCommon_proto_rawDescData = protoimpl.X.CompressGZIP(file_SocketCommon_proto_rawDescData)
	})
	return file_SocketCommon_proto_rawDescData
}

var file_SocketCommon_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_SocketCommon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SocketCommon_proto_goTypes = []any{
	(SocketCommon_Command)(0),   // 0: com.tigerbrokers.stock.openapi.client.socket.data.pb.SocketCommon.Command
	(SocketCommon_DataType)(0),  // 1: com.tigerbrokers.stock.openapi.client.socket.data.pb.SocketCommon.DataType
	(SocketCommon_QuoteType)(0), // 2: com.tigerbrokers.stock.openapi.client.socket.data.pb.SocketCommon.QuoteType
	(*SocketCommon)(nil),        // 3: com.tigerbrokers.stock.openapi.client.socket.data.pb.SocketCommon
}
var file_SocketCommon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SocketCommon_proto_init() }
func file_SocketCommon_proto_init() {
	if File_SocketCommon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SocketCommon_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SocketCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SocketCommon_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SocketCommon_proto_goTypes,
		DependencyIndexes: file_SocketCommon_proto_depIdxs,
		EnumInfos:         file_SocketCommon_proto_enumTypes,
		MessageInfos:      file_SocketCommon_proto_msgTypes,
	}.Build()
	File_SocketCommon_proto = out.File
	file_SocketCommon_proto_rawDesc = nil
	file_SocketCommon_proto_goTypes = nil
	file_SocketCommon_proto_depIdxs = nil
}
