// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.3
// source: StockTopData.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockTopData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market    string                  `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Timestamp int64                   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TopData   []*StockTopData_TopData `protobuf:"bytes,3,rep,name=topData,proto3" json:"topData,omitempty"`
}

func (x *StockTopData) Reset() {
	*x = StockTopData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StockTopData_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockTopData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTopData) ProtoMessage() {}

func (x *StockTopData) ProtoReflect() protoreflect.Message {
	mi := &file_StockTopData_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTopData.ProtoReflect.Descriptor instead.
func (*StockTopData) Descriptor() ([]byte, []int) {
	return file_StockTopData_proto_rawDescGZIP(), []int{0}
}

func (x *StockTopData) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *StockTopData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StockTopData) GetTopData() []*StockTopData_TopData {
	if x != nil {
		return x.TopData
	}
	return nil
}

type StockTopData_TopData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetName string                    `protobuf:"bytes,1,opt,name=targetName,proto3" json:"targetName,omitempty"` // changeRate, changeRate5Min, turnoverRate, amount, volume, amplitude
	Item       []*StockTopData_StockItem `protobuf:"bytes,2,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *StockTopData_TopData) Reset() {
	*x = StockTopData_TopData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StockTopData_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockTopData_TopData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTopData_TopData) ProtoMessage() {}

func (x *StockTopData_TopData) ProtoReflect() protoreflect.Message {
	mi := &file_StockTopData_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTopData_TopData.ProtoReflect.Descriptor instead.
func (*StockTopData_TopData) Descriptor() ([]byte, []int) {
	return file_StockTopData_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StockTopData_TopData) GetTargetName() string {
	if x != nil {
		return x.TargetName
	}
	return ""
}

func (x *StockTopData_TopData) GetItem() []*StockTopData_StockItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type StockTopData_StockItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LatestPrice float64 `protobuf:"fixed64,2,opt,name=latestPrice,proto3" json:"latestPrice,omitempty"`
	TargetValue float64 `protobuf:"fixed64,3,opt,name=targetValue,proto3" json:"targetValue,omitempty"`
}

func (x *StockTopData_StockItem) Reset() {
	*x = StockTopData_StockItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_StockTopData_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockTopData_StockItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockTopData_StockItem) ProtoMessage() {}

func (x *StockTopData_StockItem) ProtoReflect() protoreflect.Message {
	mi := &file_StockTopData_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockTopData_StockItem.ProtoReflect.Descriptor instead.
func (*StockTopData_StockItem) Descriptor() ([]byte, []int) {
	return file_StockTopData_proto_rawDescGZIP(), []int{0, 1}
}

func (x *StockTopData_StockItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockTopData_StockItem) GetLatestPrice() float64 {
	if x != nil {
		return x.LatestPrice
	}
	return 0
}

func (x *StockTopData_StockItem) GetTargetValue() float64 {
	if x != nil {
		return x.TargetValue
	}
	return 0
}

var File_StockTopData_proto protoreflect.FileDescriptor

var file_StockTopData_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x54, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x34, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x67, 0x65, 0x72, 0x62,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x6f, 0x70, 0x65,
	0x6e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x62, 0x22, 0xa1, 0x03, 0x0a, 0x0c, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x54, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x64, 0x0a, 0x07, 0x74, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x67, 0x65, 0x72, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x54,
	0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x54, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07,
	0x74, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x8b, 0x01, 0x0a, 0x07, 0x54, 0x6f, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x60, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x4c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x67, 0x65, 0x72, 0x62, 0x72, 0x6f,
	0x6b, 0x65, 0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x54, 0x6f,
	0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x67, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x68,
	0x0a, 0x34, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x69, 0x67, 0x65, 0x72, 0x62, 0x72, 0x6f, 0x6b, 0x65,
	0x72, 0x73, 0x2e, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x62, 0x50, 0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x67, 0x65, 0x72, 0x66, 0x69, 0x6e, 0x74, 0x65, 0x63,
	0x68, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b,
	0x2f, 0x70, 0x75, 0x73, 0x68, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_StockTopData_proto_rawDescOnce sync.Once
	file_StockTopData_proto_rawDescData = file_StockTopData_proto_rawDesc
)

func file_StockTopData_proto_rawDescGZIP() []byte {
	file_StockTopData_proto_rawDescOnce.Do(func() {
		file_StockTopData_proto_rawDescData = protoimpl.X.CompressGZIP(file_StockTopData_proto_rawDescData)
	})
	return file_StockTopData_proto_rawDescData
}

var file_StockTopData_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_StockTopData_proto_goTypes = []any{
	(*StockTopData)(nil),           // 0: com.tigerbrokers.stock.openapi.client.socket.data.pb.StockTopData
	(*StockTopData_TopData)(nil),   // 1: com.tigerbrokers.stock.openapi.client.socket.data.pb.StockTopData.TopData
	(*StockTopData_StockItem)(nil), // 2: com.tigerbrokers.stock.openapi.client.socket.data.pb.StockTopData.StockItem
}
var file_StockTopData_proto_depIdxs = []int32{
	1, // 0: com.tigerbrokers.stock.openapi.client.socket.data.pb.StockTopData.topData:type_name -> com.tigerbrokers.stock.openapi.client.socket.data.pb.StockTopData.TopData
	2, // 1: com.tigerbrokers.stock.openapi.client.socket.data.pb.StockTopData.TopData.item:type_name -> com.tigerbrokers.stock.openapi.client.socket.data.pb.StockTopData.StockItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_StockTopData_proto_init() }
func file_StockTopData_proto_init() {
	if File_StockTopData_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_StockTopData_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StockTopData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StockTopData_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StockTopData_TopData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_StockTopData_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*StockTopData_StockItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_StockTopData_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_StockTopData_proto_goTypes,
		DependencyIndexes: file_StockTopData_proto_depIdxs,
		MessageInfos:      file_StockTopData_proto_msgTypes,
	}.Build()
	File_StockTopData_proto = out.File
	file_StockTopData_proto_rawDesc = nil
	file_StockTopData_proto_goTypes = nil
	file_StockTopData_proto_depIdxs = nil
}
